### ISSUE TITLE
Next steps?

### ISSUE THREAD

**Issue by guywire** [bottxrnife/helium-2287-w#3]
Once the miner is deployed how do you check on stats, make sure it's connected to the helium network, attach to a wallet, or enable gps?

**Comment by bottxrnife** [comment]
Currently, the Helium network only allows DIY hotspots to be packet forwarders, and cannot participate in earning rewards. You can check the sync height and name by opening an SSH terminal to the "helium-miner" instance and doing "miner info height" and "miner info name."

**Comment by mantoles** [comment]
I have a DIY hotspot and used your image.  How do I check if my package forwarder is working?
