### ISSUE TITLE
Deploy Option Throwing Error

### ISSUE THREAD

**Issue by Vestibule22** [bottxrnife/helium-2287-w#4]
I just went to deploy the update for the most recent image sent by Helium.  When I hit deploy, it will attempt to install but fail on the Wifi-Connect with the following error.  This is causing me to not be able to update the miner with the deployment.

![image](https://user-images.githubusercontent.com/68927795/113753697-3f511680-96c3-11eb-9f43-dd88100668fc.png)

**Comment by bottxrnife** [comment]
It seems like some extensions to dependencies needed to be updated in the Wi-Fi Connect script. I updated it and everything seems to work now. Thanks for noticing this issue!
