### ISSUE TITLE
Miner stuck on block 1200830 after recent deploy to fleet

### ISSUE THREAD

**Issue by Vestibule22** [bottxrnife/helium-2287-w#6]
Hotspot is stuck on block 1200830 since last night after deploying to Balena.  Attempted to revert back to an older release with no change, rebooted, and hard reboot.  Everything is still running in in the logs but stuck on that block.

**Comment by bottxrnife** [comment]
It is working fine for me, syncing to the most recent block. Maybe the database is corrupt or a worn SD card (I encountered that issue a few times). Try doing a "purge data" in balena cloud if it is still stuck but be sure to have your swarm_key backed up before as you will need to restore it.

**Comment by Vestibule22** [comment]
Ok so I have purged data and was able to get my swarm key l loaded back on it.  However, now it hasn't moved from block 1.  Is there a timeframe I should wait for before it should start syncing up?

**Comment by Vestibule22** [comment]
![Screenshot_20220128-150435_Chrome](https://user-images.githubusercontent.com/68927795/151627942-d94a126d-ccf8-4d06-b7db-29f2a3174d8a.jpg)
